/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Services.servicesBooks;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAL.bookGenre;
import DAL.author;
import DAL.bookAddress;
import DAL.publisher;
import Services.servicesAuthor;
import Services.servicesBookGenre;
import Services.servicesBookAddress;
import Services.servicesPublisher;
import java.util.ArrayList;
import Services.texts;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author fahri
 */
public class adminAddBook extends javax.swing.JFrame {

    ArrayList<bookGenre> bookGenreList = new ArrayList<>();
    ArrayList<author> authorList = new ArrayList<>();
    ArrayList<bookAddress> bookAddressColunmList = new ArrayList<>();
    ArrayList<bookAddress> bookAddressShelfList = new ArrayList<>();
    ArrayList<publisher> publisherList = new ArrayList<>();

    /**
     * Creates new form adminAddBook
     */
    public adminAddBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblBookName = new javax.swing.JLabel();
        lblBookGenreID = new javax.swing.JLabel();
        lblAuthorID = new javax.swing.JLabel();
        lblISBN_No = new javax.swing.JLabel();
        lblBookStatus = new javax.swing.JLabel();
        lblBookAddressID = new javax.swing.JLabel();
        lblPublisherID = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtISBN_No = new javax.swing.JTextField();
        txtBookStatus = new javax.swing.JTextField();
        comboBxBookGenre = new javax.swing.JComboBox<>();
        comboBxAuthor = new javax.swing.JComboBox<>();
        comboBxShelf = new javax.swing.JComboBox<>();
        comboBxColomn = new javax.swing.JComboBox<>();
        comboBxPublisher = new javax.swing.JComboBox<>();
        lblColumn = new javax.swing.JLabel();
        lblShelf = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnList = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        backPage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(new texts().panelBook()
        );
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblID.setText(new texts().ID());
        lblID.setFocusable(false);
        lblID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblBookName.setText(new texts().bookName());
        lblBookName.setFocusable(false);
        lblBookName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblBookGenreID.setText(new texts().bookGenre());
        lblBookGenreID.setFocusable(false);
        lblBookGenreID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblAuthorID.setText(new texts().authorName());
        lblAuthorID.setFocusable(false);
        lblAuthorID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblISBN_No.setText(new texts().ISBN_NO());
        lblISBN_No.setFocusable(false);
        lblISBN_No.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblBookStatus.setText(new texts().bookStatus());
        lblBookStatus.setFocusable(false);
        lblBookStatus.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblBookAddressID.setText(new texts().bookAdress());

        lblPublisherID.setText(new texts().publisher());
        lblPublisherID.setFocusable(false);
        lblPublisherID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtID.setEnabled(false);

        txtBookStatus.setText("OKULDA");

        comboBxBookGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBxAuthor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBxShelf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBxColomn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBxPublisher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblColumn.setText(new texts().columnNo());

        lblShelf.setText(new texts().shelfNo());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblBookAddressID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBxColomn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColumn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShelf)
                            .addComponent(comboBxShelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblPublisherID))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBookStatus))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblISBN_No))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblAuthorID))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBookGenreID))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBookName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblID)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID)
                            .addComponent(txtBookName)
                            .addComponent(txtISBN_No)
                            .addComponent(txtBookStatus)
                            .addComponent(comboBxBookGenre, 0, 202, Short.MAX_VALUE)
                            .addComponent(comboBxAuthor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBxPublisher, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookName))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookGenreID)
                    .addComponent(comboBxBookGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthorID)
                    .addComponent(comboBxAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblISBN_No)
                    .addComponent(txtISBN_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookStatus)
                    .addComponent(txtBookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPublisherID)
                    .addComponent(comboBxPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColumn)
                    .addComponent(lblShelf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookAddressID)
                    .addComponent(comboBxColomn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBxShelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/liste.png"))); // NOI18N
        btnList.setText(new texts().btnList());
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book-delete.png"))); // NOI18N
        btnDelete.setText(new texts().btnDelete());
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book-update.png"))); // NOI18N
        btnUpdate.setText(new texts().btnUpdate());
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book-add.png"))); // NOI18N
        btnAdd.setText(new texts().btnAdd());
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAdd)
                        .addComponent(btnList)
                        .addComponent(btnDelete)
                        .addComponent(btnUpdate))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(btnList)
                    .addGap(18, 18, 18)
                    .addComponent(btnDelete)
                    .addGap(18, 18, 18)
                    .addComponent(btnUpdate)
                    .addGap(18, 18, 18)
                    .addComponent(btnAdd)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        backPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backPage.setToolTipText("");
        backPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPageActionPerformed(evt);
            }
        });

        tblBookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ));
        tblBookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBookList);
        if (tblBookList.getColumnModel().getColumnCount() > 0) {
            tblBookList.getColumnModel().getColumn(0).setHeaderValue(new texts().ID());
            tblBookList.getColumnModel().getColumn(1).setHeaderValue(new texts().bookName());
            tblBookList.getColumnModel().getColumn(2).setHeaderValue(new texts().bookGenre());
            tblBookList.getColumnModel().getColumn(3).setHeaderValue(new texts().authorName());
            tblBookList.getColumnModel().getColumn(4).setHeaderValue(new texts().ISBN_NO());
            tblBookList.getColumnModel().getColumn(5).setHeaderValue(new texts().bookStatus());
            tblBookList.getColumnModel().getColumn(6).setHeaderValue(new texts().publisher());
            tblBookList.getColumnModel().getColumn(7).setHeaderValue(new texts().columnNo());
            tblBookList.getColumnModel().getColumn(8).setHeaderValue(new texts().shelfNo());
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backPage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backPage)
                        .addGap(75, 75, 75)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblBookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookListMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblBookList.getModel();
        int selected = tblBookList.getSelectedRow();
        txtID.setText(model.getValueAt(selected, 0).toString());
        txtBookName.setText(model.getValueAt(selected, 1).toString());
        txtISBN_No.setText(model.getValueAt(selected, 4).toString());
        txtBookStatus.setText(model.getValueAt(selected, 5).toString());

        int ID = Integer.parseInt(model.getValueAt(selected, 0).toString());
        int[] bookGenre = new servicesBooks().GetBookGenreByID(ID);
        int bookGenreIndex = 0;

        for (int i = 0; i < bookGenreList.size(); i++) {
            if (bookGenreList.get(i).getBookGenreID() == bookGenre[0]) {
                bookGenreIndex = i;
                break;
            }
        }
        comboBxBookGenre.setSelectedIndex(bookGenreIndex + 1);

        int[] author = new servicesBooks().GetBookAuthorByID(ID);
        int authorIndex = 0;
        for (int i = 0; i < authorList.size(); i++) {
            if (authorList.get(i).getAuthorID() == author[0]) {
                authorIndex = i;
                break;
            }
        }
        comboBxAuthor.setSelectedIndex(authorIndex + 1);

        int[] publisher = new servicesBooks().getPublisherByID(ID);
        int publisherIndex = 0;
        for (int i = 0; i < publisherList.size(); i++) {
            if (publisherList.get(i).getPublisherID() == publisher[0]) {
                publisherIndex = i;
                break;
            }
        }
        comboBxPublisher.setSelectedIndex(publisherIndex + 1);

        int[] bookAddress = new servicesBooks().GetBookAddressByID(ID);
        int bookAdressColunmIndex = 0, bookAdressShelfIndex = 0;
        for (int i = 0; i < bookAddressColunmList.size(); i++) {
            if (bookAddressColunmList.get(i).getBookAddressID() == bookAddress[1]) {
                bookAdressColunmIndex = i;
                break;
            }
        }
        for (int i = 0; i < bookAddressShelfList.size(); i++) {
            if (bookAddressShelfList.get(i).getBookAddressID() == bookAddress[2]) {
                bookAdressShelfIndex = i;
                break;
            }
        }
        comboBxColomn.setSelectedIndex(bookAdressColunmIndex + 1);
        comboBxShelf.setSelectedIndex(bookAdressShelfIndex + 1);


    }//GEN-LAST:event_tblBookListMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        servicesBookGenre bGenre = new servicesBookGenre();
        DefaultComboBoxModel modelGenre = (DefaultComboBoxModel) comboBxBookGenre.getModel();
        bookGenreList = bGenre.load(modelGenre);

        servicesAuthor author = new servicesAuthor();
        DefaultComboBoxModel modelAuthor = (DefaultComboBoxModel) comboBxAuthor.getModel();
        authorList = author.load(modelAuthor);

        servicesPublisher publisher = new servicesPublisher();
        DefaultComboBoxModel modelPublisher = (DefaultComboBoxModel) comboBxPublisher.getModel();
        publisherList = publisher.load(modelPublisher);

        servicesBookAddress bAdressColumn = new servicesBookAddress();
        DefaultComboBoxModel modelBookColomn = (DefaultComboBoxModel) comboBxColomn.getModel();
        bookAddressColunmList = bAdressColumn.loadColl(modelBookColomn);

        servicesBookAddress bAdressShelf = new servicesBookAddress();
        DefaultComboBoxModel modelBookShelf = (DefaultComboBoxModel) comboBxShelf.getModel();
        bookAddressShelfList = bAdressShelf.loadShelf(modelBookShelf);

        List();
    }//GEN-LAST:event_formWindowOpened

    private void backPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPageActionPerformed
        // TODO add your handling code here:
        adminMainPanel panel=new adminMainPanel();
        panel.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_backPageActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String bookName = txtBookName.getText().trim();
        String ISBN_No = txtISBN_No.getText().trim();
        String bookStatus = txtBookStatus.getText().trim();
        int ISBN_no = Integer.parseInt(ISBN_No);
        int colunmNumber = comboBxColomn.getSelectedIndex();
        String col = String.valueOf(colunmNumber);
        int shelfNumber = comboBxShelf.getSelectedIndex();
        int bookGenreIndex = comboBxBookGenre.getSelectedIndex();
        if (bookGenreIndex <= 0) {
            JOptionPane.showMessageDialog(null, new texts().selectLine());
            return;
        }
        bookGenre bookGenre = bookGenreList.get(bookGenreIndex - 1);

        int authorIndex = comboBxAuthor.getSelectedIndex();
        if (authorIndex <= 0) {
            JOptionPane.showMessageDialog(null, new texts().selectLine());
            return;
        }
        DAL.author valueOfAuthor = authorList.get(authorIndex - 1);

        int publisherIndex = comboBxPublisher.getSelectedIndex();
        if (publisherIndex <= 0) {
            JOptionPane.showMessageDialog(null, new texts().selectLine());
            return;
        }
        DAL.publisher valueOfPublisher = publisherList.get(publisherIndex - 1);
        new servicesBooks().vtAdd(bookName, bookGenre.getBookGenreID(), valueOfAuthor.getAuthorID(), ISBN_no, bookStatus, valueOfPublisher.getPublisherID(), col, shelfNumber);

        List();
        Clean();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String SelectedID = txtID.getText().trim();
        if (SelectedID != null) {
            String bookName = txtBookName.getText().trim();
            String ISBN_No = txtISBN_No.getText().trim();
            String bookStatus = txtBookStatus.getText().trim();

            int ID = Integer.parseInt(SelectedID);
            int ISBN_no = Integer.parseInt(ISBN_No);
            int colunmNumber = comboBxColomn.getSelectedIndex();
            String col = String.valueOf(colunmNumber);
            int shelfNumber = comboBxShelf.getSelectedIndex();
            int bookGenreIndex = comboBxBookGenre.getSelectedIndex();
            if (bookGenreIndex <= 0) {
                JOptionPane.showMessageDialog(null, new texts().selectLine());
                return;
            }
            DAL.bookGenre valueOfBookGenre = bookGenreList.get(bookGenreIndex - 1);

            int authorIndex = comboBxAuthor.getSelectedIndex();
            if (authorIndex <= 0) {
                JOptionPane.showMessageDialog(null, new texts().selectLine());
                return;
            }
            DAL.author valueOfAuthor = authorList.get(authorIndex - 1);

            int publisherIndex = comboBxPublisher.getSelectedIndex();
            if (publisherIndex <= 0) {
                JOptionPane.showMessageDialog(null, new texts().selectLine());
                return;
            }
            DAL.publisher valueOfPublisher = publisherList.get(publisherIndex - 1);

            new servicesBooks().vtUpdate(ID, bookName, valueOfBookGenre.getBookGenreID(), valueOfAuthor.getAuthorID(), ISBN_no, bookStatus, valueOfPublisher.getPublisherID(), col, shelfNumber);

            List();
            Clean();
        } else {
            JOptionPane.showMessageDialog(null, new texts().selectLine());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String SelectedID = txtID.getText().trim();
        if (SelectedID != null) {
            int ID = Integer.parseInt(SelectedID);
            new servicesBooks().vtDelete(ID);
            List();
            Clean();
        } else {
            JOptionPane.showMessageDialog(null, new texts().selectLine());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        List();
        Clean();
    }//GEN-LAST:event_btnListActionPerformed

    public void Clean() {
        txtID.setText("");
        txtBookName.setText("");
        txtBookStatus.setText("OKULDA");
        txtISBN_No.setText("");
        comboBxBookGenre.setSelectedIndex(0);
        comboBxAuthor.setSelectedIndex(0);
        comboBxColomn.setSelectedIndex(0);
        comboBxShelf.setSelectedIndex(0);
        comboBxPublisher.setSelectedIndex(0);

    }

    public void List() {
        DefaultTableModel model = (DefaultTableModel) tblBookList.getModel();
        new servicesBooks().bring(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminAddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminAddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backPage;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboBxAuthor;
    private javax.swing.JComboBox<String> comboBxBookGenre;
    private javax.swing.JComboBox<String> comboBxColomn;
    private javax.swing.JComboBox<String> comboBxPublisher;
    private javax.swing.JComboBox<String> comboBxShelf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthorID;
    private javax.swing.JLabel lblBookAddressID;
    private javax.swing.JLabel lblBookGenreID;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblBookStatus;
    private javax.swing.JLabel lblColumn;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblISBN_No;
    private javax.swing.JLabel lblPublisherID;
    private javax.swing.JLabel lblShelf;
    private javax.swing.JTable tblBookList;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtBookStatus;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtISBN_No;
    // End of variables declaration//GEN-END:variables
}
