/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Services.texts;

/**
 *
 * @author fahri
 */
public class adminMainPanel extends javax.swing.JFrame {

    /**
     * Creates new form adminMainPanel
     */
    public adminMainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPage = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAddBook = new javax.swing.JButton();
        btnAuthor = new javax.swing.JButton();
        btnBookGenre = new javax.swing.JButton();
        btnPublisher = new javax.swing.JButton();
        btnBookAddress = new javax.swing.JButton();
        btnStudentsList = new javax.swing.JButton();
        btnOfficerList = new javax.swing.JButton();
        btnDepartmentList = new javax.swing.JButton();
        btnBookDeliverySettings = new javax.swing.JButton();
        btnFaculty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(new texts().PanelAdminMain());

        backPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backPage.setToolTipText("");
        backPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPageActionPerformed(evt);
            }
        });

        btnAddBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book-add.png"))); // NOI18N
        btnAddBook.setText(new texts().panelBook());
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/author.png"))); // NOI18N
        btnAuthor.setText(new texts().panelAuthor());
        btnAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorActionPerformed(evt);
            }
        });

        btnBookGenre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book.png"))); // NOI18N
        btnBookGenre.setText(new texts().panelBookGenre());
        btnBookGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookGenreActionPerformed(evt);
            }
        });

        btnPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book.png"))); // NOI18N
        btnPublisher.setText(new texts().panelPublisher());
        btnPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherActionPerformed(evt);
            }
        });

        btnBookAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book-address.png"))); // NOI18N
        btnBookAddress.setText(new texts().panelBookAdress());
        btnBookAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAddressActionPerformed(evt);
            }
        });

        btnStudentsList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graduated.png"))); // NOI18N
        btnStudentsList.setText(new texts().panelStudent());
        btnStudentsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsListActionPerformed(evt);
            }
        });

        btnOfficerList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employee.png"))); // NOI18N
        btnOfficerList.setText(new texts().panelAdminList());
        btnOfficerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfficerListActionPerformed(evt);
            }
        });

        btnDepartmentList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graduate.png"))); // NOI18N
        btnDepartmentList.setText(new texts().panelDepartment());
        btnDepartmentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentListActionPerformed(evt);
            }
        });

        btnBookDeliverySettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book-settings.png"))); // NOI18N
        btnBookDeliverySettings.setText(new texts().panelBookDeliverySetting());
        btnBookDeliverySettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookDeliverySettingsActionPerformed(evt);
            }
        });

        btnFaculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graduate.png"))); // NOI18N
        btnFaculty.setText(new texts().facultyName());
        btnFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddBook)
                    .addComponent(btnAuthor)
                    .addComponent(btnBookAddress))
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPublisher)
                    .addComponent(btnBookGenre)
                    .addComponent(btnDepartmentList)
                    .addComponent(btnFaculty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnOfficerList, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnStudentsList, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnBookDeliverySettings))
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBookGenre)
                            .addComponent(btnOfficerList))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStudentsList)
                            .addComponent(btnAuthor)
                            .addComponent(btnPublisher)))
                    .addComponent(btnAddBook))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBookAddress)
                    .addComponent(btnDepartmentList)
                    .addComponent(btnBookDeliverySettings))
                .addGap(18, 18, 18)
                .addComponent(btnFaculty)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(backPage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(backPage)
                .addGap(157, 157, 157)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:
        adminAddBook panel = new adminAddBook();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnOfficerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfficerListActionPerformed
        // TODO add your handling code here:
        adminList panel = new adminList();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOfficerListActionPerformed

    private void btnStudentsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsListActionPerformed
        // TODO add your handling code here:
        adminStudentList panel = new adminStudentList();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStudentsListActionPerformed

    private void btnBookAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAddressActionPerformed
        // TODO add your handling code here:
        adminBookAddress panel = new adminBookAddress();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBookAddressActionPerformed

    private void btnPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherActionPerformed
        // TODO add your handling code here:
        adminPublisher panel = new adminPublisher();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPublisherActionPerformed

    private void btnBookGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookGenreActionPerformed
        // TODO add your handling code here:
        adminBookGenre panel = new adminBookGenre();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBookGenreActionPerformed

    private void btnAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorActionPerformed
        // TODO add your handling code here:
        adminAuthor panel = new adminAuthor();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAuthorActionPerformed

    private void btnDepartmentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentListActionPerformed
        // TODO add your handling code here:
        adminDepartment panel = new adminDepartment();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDepartmentListActionPerformed

    private void backPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPageActionPerformed
        // TODO add your handling code here:
        adminEntry panel = new adminEntry();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backPageActionPerformed

    private void btnBookDeliverySettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookDeliverySettingsActionPerformed
        // TODO add your handling code here:
        adminBookDeliverySettings panel = new adminBookDeliverySettings();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBookDeliverySettingsActionPerformed

    private void btnFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyActionPerformed
        // TODO add your handling code here:
        adminFaculty panel = new adminFaculty();
        panel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFacultyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backPage;
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnAuthor;
    private javax.swing.JButton btnBookAddress;
    private javax.swing.JButton btnBookDeliverySettings;
    private javax.swing.JButton btnBookGenre;
    private javax.swing.JButton btnDepartmentList;
    private javax.swing.JButton btnFaculty;
    private javax.swing.JButton btnOfficerList;
    private javax.swing.JButton btnPublisher;
    private javax.swing.JButton btnStudentsList;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
